config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :groups do
    member do
      post :join
      post :quit
    end

    resources :posts, except: [:destroy] do
      member do
        post :manage
      end
    end
  end

  namespace :account do
    resources :groups, only: [:index]
    resources :posts, only: [:index, :edit, :update, :destroy]
  end

  root "groups#index"
end

app/models/group.rb
# frozen_string_literal: true
class Group < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :delete_all
  has_many :group_relationships, dependent: :delete_all
  has_many :members, through: :group_relationships, source: :user

  validates :title, presence: true

  scope :recent, -> { order(updated_at: :desc) }
end

app/controllers/account/groups_controller.rb
# frozen_string_literal: true
class Account::GroupsController < ApplicationController
  before_action :authenticate_user!

  def index
    @groups = current_user.participated_groups
  end
end

app/controllers/groups_controller.rb
# frozen_string_literal: true
class GroupsController < ApplicationController
  before_action(:find_group, only: [:show, :edit, :update, :destroy, :join, :quit])
  before_action(:authenticate_user!, only: [:new, :create, :edit, :update, :destroy])
  before_action(:check_owner, only: [:edit, :update, :destroy])
  before_action(:authenticate_user!, only: [:join, :quit])

  def index
    @groups = Group.includes(:user).recent
  end

  def show
    @owner_verify_posts = @group.posts.where(status: [Post::OWNER_STATUS]).includes(:user).recent
    @current_user_posts = @group.posts.where(status: [Post::CURRENT_USER_STATUS], user: current_user).includes(:user).recent
    @publish_posts = @group.posts.where(status: [Post::PUBLISH_STATUS]).includes(:user).recent.page(params[:page]).per(20)
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)

    if @group.save
      current_user.join!(@group)
      redirect_to(groups_path, notice: "新增群組成功")
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to(groups_path, notice: "更新群組成功")
    else
      render "edit"
    end
  end

  def destroy
    @group.destroy
    redirect_to(groups_path, alert: "Group deleted")
  end

  def join
    if !current_user.is_member_of?(@group)
      current_user.join!(@group)
      flash[:notice] = "加入群組成功！"
    else
      flash[:warning] = "你已經是本群組成員了！"
    end

    redirect_to group_path(@group)
  end

  def quit
    if current_user.is_member_of?(@group)
      current_user.quit!(@group)
      flash[:alert] = "已退出群組！"
    else
      flash[:warning] = "非群組成員，無法退出"
    end

    redirect_to group_path(@group)
  end

  private

  def group_params
    params.require(:group).permit(:title, :description)
  end

  def find_group
    @group = Group.find(params[:id])
  end

  def check_owner
    return redirect_to(root_path, alert: "使用者無權限，請先加入群組") if current_user != @group.user
  end
end

app/helpers/groups_helper.rb
# frozen_string_literal: true
module GroupsHelper
  def render_group_description(group)
    simple_format(group.description)
  end
end

app/views/groups/_group_item.html.erb
<% groups.each do |group| %>
  <tr>
    <td>#</td>
    <td><%= link_to(group.title, group_path(group)) %></td>
    <td><%= render_group_description(group) %></td>
    <td><%= group.user.email %></td>
    <td>
      <% if current_user && group.owner?(current_user) %>
        <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default")%>
        <%= link_to("Delete", group_path(group), class: "btn btn-sm btn-default", method: :delete, data: { confirm: "Are you sure?" })%>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/groups/edit.html.erb
<%= render("common/form", group: @group, submit: "確定修改") %>

app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group d-flex justify-content-end my-5">
    <%= link_to("New group", new_group_path, class: "btn btn-primary") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
        <td>Creator</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <%= render("groups/group_item", groups: @groups) %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>新增討論版</h2>
  <hr>
  <%= render("common/form", group: @group, submit: "新增討論版") %>
</div>

app/views/groups/show.html.erb
<% is_in_group = current_user && current_user.is_member_of?(@group) %>

<div class="col-md 12">
  <h2><%= @group.title %></h2>

  <div class="group">
    <span class="float-end">
      <% if is_in_group %>
        <label class="label label-success">群組成員</label>
        <%= link_to("離開群組", quit_group_path(@group), method: :post, class: "btn btn-default") %>
      <% else %>
        <label class="label label-warning">非群組成員</label>
        <%= link_to("加入群組", join_group_path(@group), method: :post, class: "btn btn-default") %>
      <% end %>
    </span>
  </div>
  <div class="group">
    <% if is_in_group %>
      <%= link_to("新增文章", new_group_post_path(@group), class: "btn btn-default float-end" ) %>
    <% end %>
  </div>
  <% if current_user && current_user == @group.user %>
    <%= link_to("編輯", edit_group_path(@group), class: "btn btn-primary float-end") %>
  <% end %>

  <% if @group.user == current_user %>
    <h2>待審核文章（管理員）</h2>
    <table class="table">
      <thead>
        <tr>
          <th>文章內容</th>
          <th>作者</th>
          <th>時間</th>
          <th colspan="3">操作</th>
        </tr>
      </thead>
      <tbody>
        <% @owner_verify_posts.each do |post| %>
          <tr>
            <td><%= post.content %></td>
            <td><%= post.user.email %></td>
            <td><%= post.updated_at %></td>
            <td><%= button_to("審核通過", manage_group_post_path(@group, post, post:{status: "publish"}))%></td>
            <td><%= button_to("審核失敗", manage_group_post_path(@group, post, post:{status: post.pendding? ? "decline" : "update_fail"}))%></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <table class="table">
    <h2>待審核文章（用戶）</h2>
    <thead>
      <tr>
        <th>狀態</th>
        <th>文章內容</th>
        <th>作者</th>
        <th>時間</th>
        <th colspan="3">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @current_user_posts.each do |post| %>
        <tr>
          <td><%= post.status %></td>
          <td><%= post.content %></td>
          <td><%= post.user.email %></td>
          <td><%= post.updated_at %></td>
          <% if post.author_posts? %>
            <td><%= button_to("提交申請", manage_group_post_path(@group, post, post: {status: "pendding"}))%></td>
          <% else %>
            <td><%= button_to("取消申請審核", manage_group_post_path(@group, post, post: {status: post.published? ? "cancel_update_verify" : "draft"}))%></td>
          <% end %>
          <td><%= link_to("編輯", edit_group_post_path(@group, post)) %></td>
          <td><%= button_to("刪除", manage_group_post_path(@group, post, post: {status: post.draft? ? "trash" : "delete_by_user" }), data: { confirm: "確定要刪除嗎？"})%></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <table class="table">
    <h2>文章列表</h2>
    <thead>
      <tr>
        <th>文章內容</th>
        <th>作者</th>
        <th>時間</th>
        <th>文章狀態</th>
        <th colspan="5">操作</th>
      </tr>
    </thead>
    <tbody>
      <% @publish_posts.each do |post| %>
        <tr>
          <td>
            <% if read_authorization(post) %>
              <%= post.content %>
            <% else %>
              -
            <% end %>
          </td>
          <td><%= post.user.email %></td>
          <td><%= post.updated_at %></td>
          <td><%= post_status_message(post.status) %></td>
          <% if post.editable? && current_user_post?(post.user) %>
            <td><%= link_to("編輯", edit_group_post_path(@group, post, post: {status: "update_post"})) %></td>
            <td><%= button_to("刪除", manage_group_post_path(@group, post, post: {status: delete_by(post.user)}), data: { confirm: "確定要刪除嗎？"})%></td>
          <% end %>
          <td>
            <% if group_owner?(@group) && post.may_block? %>
              <%= button_to("封鎖", manage_group_post_path(@group, post, post: {status: "block"}), data: { confirm: "確定要刪除嗎？"})%>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div>
    <%= paginate @publish_posts  %>
  </div>
</div>